name: Simple Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build for production
      run: npm run build -- --configuration production --base-href "/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)/"
      
    - name: Create 404.html from index.html
      run: cp dist/fusion-angular-tailwind-starter/browser/index.html dist/fusion-angular-tailwind-starter/browser/404.html
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/fusion-angular-tailwind-starter/browser
        force_orphan: true
